### ISSUE TITLE
No argument parsing in preprocess_birdclef.py

### ISSUE THREAD

**Issue by julj** [johnmartinsson/bird-species-classification#22]
So

```
$ python preprocess_birdclef.py --xml_dir=<path-to-xml-dir> \
                                --wav_dir=<path-to-wav-dir> \
                                --output_dir=<path-to-output-dir>
```

still use hardcoded path...

**Comment by johnmartinsson** [comment]
Thank you for raising these issues. It may be that the documentation is not up to date and that you should use
''' python
 create_dataset.py 
'''
instead. I am out traveling right now and cannot look much deeper into these issues right now. I should take the time to clean the repo and test all scripts when I get home.

**Comment by johnmartinsson** [comment]
The problem was that the code was not up to date. I had forgotten to push my last work. The issue should now be resolved.
