### ISSUE TITLE
Wrong variable in preprocess_birdclef.py

### ISSUE THREAD

**Issue by julj** [johnmartinsson/bird-species-classification#23]
`xml_paths` should be replaced by `xml_roots` in https://github.com/johnmartinsson/bird-species-classification/blob/master/preprocess_birdclef.py#L36.

Maybe you should run your code once to test it?

**Comment by johnmartinsson** [comment]
Thank you for raising the issue. The documention and the code may not be synced. I will look into this when I can (right now I am without a computer and on an two week vacation).

**Comment by johnmartinsson** [comment]
I had forgotten to push my last work. I may work as expected now, but I have not tested it yet.

**Comment by johnmartinsson** [comment]
This works as expected now that the latest code has been pushed.
