### ISSUE TITLE
weight files seems to be missing

### ISSUE THREAD

**Issue by subhadeepkaran** [johnmartinsson/bird-species-classification#28]
Possible issue may arise due to updates in "wave" file reading libraries

**Comment by johnmartinsson** [comment]
Hi! Did you find a solution? I would love to know if you manage to get the code to run. 

I have not actively maintained the code, but if there are any easy fixes I could possibly take a stab at it.

Best,
J.

**Comment by subhadeepkaran** [comment]
Hey hi,

thanks for sharing work. i am quite curious to see how it works.

Though, I haven't yet able to get the code working out of the box.

Initially, I believe the issue started with reading of the wave files.

It seems scipy has updated their library and it barks on me as when you read with scipy it gives back a numpy array of int's instead of floating which is required by librosa.

If you can look at it, it would be great.

**Comment by johnmartinsson** [comment]
This should be solved now that the requirements.txt file contains the exact versions of the libraries used during the thesis work.
