### ISSUE TITLE
Version of the pre-requisites 

### ISSUE THREAD

**Issue by subhadeepkaran** [johnmartinsson/bird-species-classification#29]
Can you mention the version of the pre-requisites on which the code works?

I can understand it will take some time and effort to update the repo reflect the changes in API.

I found 2 issues in trying to run the code out of box.

First, was in signal_processing.py where librosa.stft requires numpy array in float which I managed to resolve by just adding a line 'wave = wave.astype(float)'

Second, was found in conf.ini which didn't had the optimizer mentioned I believe 'sgd' is used.

**Comment by subhadeepkaran** [comment]
Regarding versions:

Had to update the requirements.txt with the lines to get the code working:
tensorflow==1.0
keras==1.2

**Comment by johnmartinsson** [comment]
Hi! Thank you very much for looking into this. I was just pulling down an old requirements file from the computer that I used during my thesis.

I will update the requirements to the frozen version of the virtualenv I used 2 years ago. This is a good suggestion, and something I should have done from the start.

I take it that you have solved the problem and that I can resolve this issue?

**Comment by subhadeepkaran** [comment]
> I take it that you have solved the problem and that I can resolve this issue?

No. I believe its resolved
